import type { Metadata, Viewport } from 'next';
import './globals.css';
import AppShell from '@/components/AppShell';

export const metadata: Metadata = {
  title: 'CoachMind — Professional Coaching Platform',
  description: 'The professional coaching platform for modern football coaches',
  applicationName: 'CoachMind',
  // App manifest — generated by src/app/manifest.ts (Next 14 metadata route)
  manifest: '/manifest.webmanifest',
  // iOS / iPad — required for full-screen Add-to-Home-Screen behaviour
  appleWebApp: {
    capable: true,
    title: 'CoachMind',
    statusBarStyle: 'black-translucent',
  },
  // Prevent iOS Safari from auto-linking phone-number-ish strings in coaching notes
  formatDetection: { telephone: false },
  // Icons — auto-discovered from src/app/icon.tsx and src/app/apple-icon.tsx,
  // but listed here too for browsers that look at <head> first.
  icons: {
    icon: '/icon',
    apple: '/apple-icon',
  },
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Allow zoom — coaches may want to pinch in on a print preview.
  // Pinch on the drawing canvas is overridden separately (touch-action: none).
  maximumScale: 5,
  // Extend behind iPad notches / home-indicator. Combined with env(safe-area-inset-*)
  // in globals.css.
  viewportFit: 'cover',
  // Matches the app's dark background — controls iOS status-bar colour in
  // full-screen mode and the Android Chrome address-bar colour.
  themeColor: '#080c14',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-[#080c14]">
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
